---
# gateway配置文件
# 重命名为: config.yml

addr: 0.0.0.0:5533
readTimeout: 60m
writeTimeout: 60m

targets:
  - name: test   # agent主机名
    address: http://127.0.0.1:5544  # agent服务请求接口

  - name: web   # agent主机名
    address: http://192.168.165.87:5544

  - name: backend
    address: http://192.168.165.89:5544